[package]
name = "rust-poc"
version = "1.0.0"
edition = "2018"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
actix-web = "3.3.2"
async-std = "1.9.0"
local-ip-address = "0.4.4"
